# syntax = docker/dockerfile:experimental
FROM osrf/ros:noetic-desktop-full-focal

# Arguments
ARG USER=initial
ARG GROUP=initial
ARG UID=1000
ARG GID=${UID}
ARG SHELL=/bin/bash
# Env vars for the nvidia-container-runtime.
ENV NVIDIA_VISIBLE_DEVICES all
ENV NVIDIA_DRIVER_CAPABILITIES graphics,utility,compute
# Setup users and groups
RUN groupadd --gid ${GID} ${GROUP} \
  && useradd --gid ${GID} --uid ${UID} -ms ${SHELL} ${USER} \
  && mkdir -p /etc/sudoers.d \
  && echo "${USER}:x:${UID}:${UID}:${USER},,,:$HOME:${shell}" >> /etc/passwd \
  && echo "${USER}:x:${UID}:" >> /etc/group \
  && echo "${USER} ALL=(ALL) NOPASSWD: ALL" > "/etc/sudoers.d/${USER}" \
  && chmod 0440 "/etc/sudoers.d/${USER}"

# Replace apt urls
RUN sed -i 's@archive.ubuntu.com@ftp.tku.edu.tw/@g' /etc/apt/sources.list
# Install packages
RUN apt-get update && apt-get install -y --no-install-recommends \
      terminator gnome-terminal dbus-x11 libglvnd0 libgl1 libglx0 libegl1 libxext6 libx11-6 \
      ssh byobu nano git sudo wget rsync net-tools \
      python3-pip python3-catkin-tools ros-noetic-gazebo-ros-pkgs \
      ros-noetic-effort-controllers \
  && apt-get clean \
  && rm -rf /var/lib/apt/lists/*

# setup custom configuration
COPY config /home/${USER}/.tmp
RUN cat /home/${USER}/.tmp/bashrc/* >> /home/${USER}/.bashrc \
  && pip3 install -r /home/${USER}/.tmp/pip/requirements.txt \
  && mkdir -p /home/${USER}/.config/terminator \
  && cp -r /home/${USER}/.tmp/terminator /home/${USER}/.config/terminator \
  && chown -R ${USER}:${GROUP} /home/${USER}/.config \
  && mkdir -p /etc/udev/rules.d/ \
  && cp /home/${USER}/.tmp/rule/* /etc/udev/rules.d/ \
  && rm -rf /home/${USER}/.tmp

# Switch user to ${USER}
USER ${USER}
RUN sudo mkdir work

# Make SSH available
EXPOSE 22

# Switch to user's HOME folder
WORKDIR /home/${USER}/work

# ENTRYPOINT ["terminator"]
ENTRYPOINT ["byobu"]
