# TCL File Generated by Component Editor 13.0sp1
# Mon May 31 10:36:57 CST 2021
# DO NOT MODIFY


# 
# MotorDriverReg "MotorDriverReg" v2.0
#  2021.05.31.10:36:57
# add gsensor
# 

# 
# request TCL package from ACDS 13.1
# 
package require -exact qsys 13.1


# 
# module MotorDriverReg
# 
set_module_property DESCRIPTION "add gsensor"
set_module_property NAME MotorDriverReg
set_module_property VERSION 2.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME MotorDriverReg
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property ANALYZE_HDL AUTO
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL motorX4_avs_if
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
add_fileset_file motorX4_avs_if.v VERILOG PATH ../ip/motor/motorX4_avs_if.v TOP_LEVEL_FILE


# 
# parameters
# 


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset_n reset_n Input 1


# 
# connection point s1
# 
add_interface s1 avalon end
set_interface_property s1 addressUnits WORDS
set_interface_property s1 associatedClock clock
set_interface_property s1 associatedReset reset
set_interface_property s1 bitsPerSymbol 8
set_interface_property s1 burstOnBurstBoundariesOnly false
set_interface_property s1 burstcountUnits WORDS
set_interface_property s1 explicitAddressSpan 0
set_interface_property s1 holdTime 0
set_interface_property s1 linewrapBursts false
set_interface_property s1 maximumPendingReadTransactions 0
set_interface_property s1 readLatency 2
set_interface_property s1 readWaitTime 1
set_interface_property s1 setupTime 0
set_interface_property s1 timingUnits Cycles
set_interface_property s1 writeWaitTime 0
set_interface_property s1 ENABLED true
set_interface_property s1 EXPORT_OF ""
set_interface_property s1 PORT_NAME_MAP ""
set_interface_property s1 SVD_ADDRESS_GROUP ""

add_interface_port s1 avs_s1_address address Input 5
add_interface_port s1 avs_s1_byteenable byteenable Input 4
add_interface_port s1 avs_s1_read read Input 1
add_interface_port s1 avs_s1_write write Input 1
add_interface_port s1 avs_s1_waitrequest waitrequest Output 1
add_interface_port s1 avs_s1_readdata readdata Output 32
add_interface_port s1 avs_s1_writedata writedata Input 32
set_interface_assignment s1 embeddedsw.configuration.isFlash 0
set_interface_assignment s1 embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment s1 embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment s1 embeddedsw.configuration.isPrintableDevice 0


# 
# connection point export_s1
# 
add_interface export_s1 conduit end
set_interface_property export_s1 associatedClock clock
set_interface_property export_s1 associatedReset reset
set_interface_property export_s1 ENABLED true
set_interface_property export_s1 EXPORT_OF ""
set_interface_property export_s1 PORT_NAME_MAP ""
set_interface_property export_s1 SVD_ADDRESS_GROUP ""

add_interface_port export_s1 avs_s1_export_oPWMduty export Output 32
add_interface_port export_s1 avs_s1_export_oMotorDir export Output 32
add_interface_port export_s1 avs_s1_export_iMotorFBDirection export Input 32
add_interface_port export_s1 avs_s1_export_oMotorCtrl export Output 32
add_interface_port export_s1 avs_s1_export_iMotorA_Encoder export Input 32
add_interface_port export_s1 avs_s1_export_iMotorA_Speed export Input 32
add_interface_port export_s1 avs_s1_export_iMotorA_Sensor export Input 34
add_interface_port export_s1 avs_s1_export_iMotorB_Encoder export Input 32
add_interface_port export_s1 avs_s1_export_iMotorB_Speed export Input 32
add_interface_port export_s1 avs_s1_export_iMotorB_Sensor export Input 34
add_interface_port export_s1 avs_s1_export_iMotorC_Encoder export Input 32
add_interface_port export_s1 avs_s1_export_iMotorC_Speed export Input 32
add_interface_port export_s1 avs_s1_export_iMotorC_Sensor export Input 34
add_interface_port export_s1 avs_s1_export_iMotorD_Encoder export Input 32
add_interface_port export_s1 avs_s1_export_iMotorD_Speed export Input 32
add_interface_port export_s1 avs_s1_export_iMotorD_Sensor export Input 34
add_interface_port export_s1 avs_s1_export_iMotorFifoStatus export Input 32
add_interface_port export_s1 avs_s1_export_iMotorClk export Input 1
add_interface_port export_s1 avs_s1_export_iIMUAcc export Input 32
add_interface_port export_s1 avs_s1_export_iIMUGYro export Input 32
add_interface_port export_s1 avs_s1_export_iIMUMagn export Input 32

